// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/87a5be72a9ba05815e517c0fec123b9161e37002/d3/d3.d.ts
// Type definitions for d3JS
// Project: http://d3js.org/
// Definitions by: Alex Ford <https://github.com/gustavderdrache>, Boris Yankov <https://github.com/borisyankov>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

/// <reference path="typings/main.d.ts" />
declare var __VERSION__: string;

export var version: string = __VERSION__;
export * from "./arrays/bisect";
export * from "./arrays/deviation";
export * from "./arrays/entries";
export * from "./arrays/keys";
export * from "./arrays/map";
export * from "./arrays/max";
export * from "./arrays/mean";
export * from "./arrays/median";
export * from "./arrays/merge";
export * from "./arrays/min";
export * from "./arrays/nest";
export * from "./arrays/pairs";
export * from "./arrays/quantile";
export * from "./arrays/range";
export * from "./arrays/set";
export * from "./arrays/shuffle";
export * from "./arrays/sum";
export * from "./arrays/transpose";
export * from "./arrays/values";
export * from "./arrays/variance";
export * from "./arrays/zip";

